spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.exemple.demo.controller: DEBUG
    com.exemple.demo.service: DEBUG
    com.exemple.demo.aspect: DEBUG
    com.exemple.demo.utils: DEBUG
    org.mybatis: DEBUG