spring:
  server:
    port: 80
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
logging:
  file: logs/prod_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    com.exemple.demo.controller: INFO
    com.exemple.demo.service: INFO
    com.exemple.demo.aspect: INFO
    com.exemple.demo.utils: INFO
    org.mybatis: WARN